# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='IndicadorMgr',
            new_name='Evaluacion',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='indMgr',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='nota',
        ),
        migrations.AddField(
            model_name='nota',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Evaluacion'),
        ),
        migrations.AddField(
            model_name='nota',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.Indicador'),
        ),
    ]
