# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20170110_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.TipoUsuario'),
        ),
    ]
