# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20170110_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
