# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20170131_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='puesto',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(default='', max_length=50),
        ),
    ]
