# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20170205_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='actividadPrincipal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='actividadSecundaria',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='empresaCom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='localidad',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
