# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20170305_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comentarios',
            field=models.CharField(default='', max_length=400, null=True),
        ),
    ]
