# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_profile_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='actividadSecundaria',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comentarios',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
