# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-27 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20170305_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
