# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_response_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='interviewee',
        ),
        migrations.RemoveField(
            model_name='response',
            name='interviewer',
        ),
        migrations.AlterField(
            model_name='response',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name=b'Comentarios'),
        ),
        migrations.AlterField(
            model_name='response',
            name='conditions',
            field=models.TextField(blank=True, null=True, verbose_name=b'Condiciones durante la encuesta'),
        ),
        migrations.AlterField(
            model_name='response',
            name='interview_uuid',
            field=models.CharField(max_length=36, verbose_name=b'Identificador unico de encuesta'),
        ),
    ]
