# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20170113_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='respMgr',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.ResponseMgr'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
