# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20170110_1826'),
        ('survey', '0007_auto_20170113_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemgr',
            name='organizacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responsemgr',
            name='provincia',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Provincia'),
        ),
    ]
