# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20170113_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
