# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_survey_completada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemgr',
            name='organizacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
