# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20170118_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
