# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20170119_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Subtema', 'verbose_name_plural': 'Subtemas'},
        ),
    ]
