# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20170203_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Category', verbose_name=b'Indicador'),
        ),
    ]
