# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20170203_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsemgr',
            name='organizacion',
        ),
    ]
