# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20170208_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='orden',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='orden',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
